# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ymori\git\aquarium-studio-prism-ui\AquariumPublish.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide import QtCore, QtGui

class Ui_dlg_aqPublish(object):
    def setupUi(self, dlg_aqPublish):
        dlg_aqPublish.setObjectName("dlg_aqPublish")
        dlg_aqPublish.resize(292, 450)
        self.horizontalLayout = QtGui.QHBoxLayout(dlg_aqPublish)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_title = QtGui.QLabel(dlg_aqPublish)
        self.l_title.setObjectName("l_title")
        self.verticalLayout.addWidget(self.l_title)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.l_item = QtGui.QLabel(dlg_aqPublish)
        self.l_item.setStyleSheet("color: #339af0;")
        self.l_item.setObjectName("l_item")
        self.verticalLayout.addWidget(self.l_item)
        self.cb_items = QtGui.QComboBox(dlg_aqPublish)
        self.cb_items.setObjectName("cb_items")
        self.verticalLayout.addWidget(self.cb_items)
        self.l_task = QtGui.QLabel(dlg_aqPublish)
        self.l_task.setStyleSheet("color: #339af0;")
        self.l_task.setObjectName("l_task")
        self.verticalLayout.addWidget(self.l_task)
        self.cb_task = QtGui.QComboBox(dlg_aqPublish)
        self.cb_task.setObjectName("cb_task")
        self.verticalLayout.addWidget(self.cb_task)
        self.l_description = QtGui.QLabel(dlg_aqPublish)
        self.l_description.setStyleSheet("color: #339af0;")
        self.l_description.setObjectName("l_description")
        self.verticalLayout.addWidget(self.l_description)
        self.te_description = QtGui.QPlainTextEdit(dlg_aqPublish)
        self.te_description.setObjectName("te_description")
        self.verticalLayout.addWidget(self.te_description)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.ck_thumbnail = QtGui.QCheckBox(dlg_aqPublish)
        self.ck_thumbnail.setChecked(True)
        self.ck_thumbnail.setObjectName("ck_thumbnail")
        self.verticalLayout.addWidget(self.ck_thumbnail)
        self.b_aqPublish = QtGui.QPushButton(dlg_aqPublish)
        self.b_aqPublish.setMinimumSize(QtCore.QSize(0, 35))
        self.b_aqPublish.setObjectName("b_aqPublish")
        self.verticalLayout.addWidget(self.b_aqPublish)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(dlg_aqPublish)
        QtCore.QMetaObject.connectSlotsByName(dlg_aqPublish)

    def retranslateUi(self, dlg_aqPublish):
        _translate = QtCore.QCoreApplication.translate
        dlg_aqPublish.setWindowTitle(_translate("dlg_aqPublish", "Aquarium Publish"))
        self.l_title.setText(_translate("dlg_aqPublish", "Your are publishing a media to Aquarium Studio :"))
        self.l_item.setText(_translate("dlg_aqPublish", "On this"))
        self.l_task.setText(_translate("dlg_aqPublish", "Under this task"))
        self.l_description.setText(_translate("dlg_aqPublish", "Publish description:"))
        self.ck_thumbnail.setText(_translate("dlg_aqPublish", "Update thumbnail on Aquarium"))
        self.b_aqPublish.setText(_translate("dlg_aqPublish", "Publish to Aquarium"))
